import type { FeatureKnowledge } from './types';

/** Objects (metadata-defined business objects). Admin authors; Keystone consumes as record tabs. */
export const objectsKnowledge: FeatureKnowledge = {
  id: 'objects',
  title: 'Objects (metadata objects, fields, layouts)',
  apps: ['admin', 'keystone'],
  navigation:
    'Admin: /?nav=objects&appId=<id> → Objects list; open one → object home with id=<objectId>&subTab=<key>. Keystone: objects appear as data-driven workspace tabs (?object=<api_name>).',
  matchTerms: ['object', 'objects', 'field', 'fields', 'record type', 'layout', 'metadata object', 'schema', 'picklist', 'create field', 'create object'],
  uiLevel: `ADMIN Objects list: heading "Objects"; shared list view (activeObjectApiName="object"), table mode only; "New" opens the New Object modal.
OBJECT HOME sub-tabs (RecordTabs, ids→labels, with live counts): settings→"Settings", record_types→"Record Types (N)", fields→"Fields (N)", buttons→"Buttons (N)", email_templates→"Email Templates (N)", layout→"Layout (N)", form→"Form (N)", assignments→"Assignments (N)", list_view_assignments→"List View Assignments (N)", validations→"Validation Rules (N)", triggers→"Trigger Rules (N)", audit→"Audit Log (N)". Default subtab "settings". Fields subtab has inner tabs "Fields"/"Audit Log" and a primary "New" button.
SETTINGS subtab inputs: #object-label, #object-plural-label, #object-help-text, #global-search-results-limit, #list-view-depth; checkboxes "Global search enabled","Inline edit enabled","Access log allows","Access log denies"; buttons "Save"/"Reset".
NEW OBJECT modal ("New Object", 2-step wizard "Step 1 of 2 / Object details", "Step 2 of 2 / Record naming"): #create-object-app (All-Apps only), #create-object-label (req), #create-object-api (req), #create-object-plural-label, #create-object-prefix (req, exactly 3 chars), #create-object-depth, checkboxes #create-object-search/#create-object-inline/#create-object-access-log-allow/#create-object-access-log-deny, #create-object-help-text. Footer: "Cancel"/"Back", "Next" (→"Checking..."), "Create".
FIELD modal ("New Field"/"Edit Field"): #field-label (req), #field-api-name (create) / #field-api-name-readonly (edit, IMMUTABLE), #field-type (a button aria-haspopup="listbox", placeholder "Select type", search "Search types..." — NOT a native select), then type-conditional ids (#field-required, #field-unique, #field-default-value, #field-help-text, #field-reference for lookup/master-detail, #field-formula-expression + "Verify", #field-summary-*, picklist value editor "Add value", etc.). Footer "Cancel" + "Create"/"Save".
Field types (value→label): boolean→Boolean, text→Text, textarea→Text Area, number→Number, currency→Currency, percent→Percent, date→Date, datetime→Date/Time, time→Time, email→Email, phone→Phone, url→URL, picklist→Picklist, multi_picklist→Multi List, lookup→Lookup, master_detail→Master-Detail, formula→Formula, summary→Summary, file→File, rich_textarea→Rich Text Area.
KEYSTONE: objects are workspace tabs (type "object"/"record"); record panel (ShockwaveRecordPanel) shows related lists with icon row-actions aria-label="Edit <name>"/title="Edit" and aria-label="Delete related record"/title="Delete", create button "New". Record tab context menu item: "Refresh".`,
  codeLevel: `Files: AdminObjectsPanel.tsx, AdminObjectHomePanel.tsx (subtabs ~7917, settings ~7996), AdminCreateObjectModal.tsx (~210), AdminFieldModal.tsx (type maps ~217/254, api_name read-only ~1376), main.tsx (validation ~10111, create payload ~10212); Keystone ShockwaveRecordTabs.tsx, ShockwaveRecordPanel.tsx.
Business rules: Object — Label/API Name/Prefix required; Prefix must be EXACTLY 3 chars; depth 0-10; api_name unique per app, prefix unique globally, label unique globally (case-insensitive); api_name lowercased. Field — api_name IMMUTABLE after create (read-only in edit); Master-Detail forced required & cannot self-reference; File forced not-required, needs ≥1 type + ≥1 category; Picklist needs ≥1 unique value; Number decimals 0-12, min≤max; Unique disallowed for boolean/formula/summary; type changes governed (block/migrate/lossy). "Type changes are blocked for metadata-backed objects."`,
  intentMap: [
    { saysAny: ['create object', 'new object', 'add object'], realControl: 'Objects list "New" button → "New Object" modal', accessFlow: 'nav=objects → New → fill #create-object-label/#create-object-api/#create-object-prefix → Next → Create' },
    { saysAny: ['add field', 'create field', 'new field'], realControl: 'object home → Fields subtab → "New" → "New Field" modal', accessFlow: 'open object → Fields tab → New → set #field-label, pick #field-type (listbox button), Create' },
    { saysAny: ['object settings', 'edit object'], realControl: 'object home → Settings subtab', accessFlow: 'open object → Settings → edit #object-label etc. → "Save"' },
  ],
  testNotes: `VERIFIED LIVE (2026-06-29): reach Objects by navigating directly to ?nav=objects (preserve appId) — do NOT click the sidebar (it can drift to the wrong section). The New Object field PLACEHOLDERS are example values ("Accounts"/"account"/"acc"/"5"), NOT the field names — locate fields by their #id (#create-object-label, #create-object-api, #create-object-prefix, #create-object-depth) or getByLabel("Label"/"API Name"/"Prefix"); never getByPlaceholder("Label"). Field "Type" is a searchable listbox BUTTON (aria-haspopup="listbox"), not a <select> — open it and pick by option text, do not selectOption. api_name fields are immutable on edit (read-only). Prefix validation: exactly 3 chars. Assert create success via the new row appearing in the list / the new tab opening.`,
};
